"""check client_uuid and one open check per table

Revision ID: 292fb55f28d9
Revises: b29d0404d06b
Create Date: 2026-08-09 21:16:39.751317
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '292fb55f28d9'
down_revision: Union[str, None] = 'b29d0404d06b'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dining_check', sa.Column('client_uuid', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_check_open_table'), table_name='dining_check', postgresql_where="(status = 'open'::text)")
    op.create_index('uq_check_open_per_table', 'dining_check', ['table_id'], unique=True, postgresql_where="status = 'open' AND table_id IS NOT NULL")
    op.create_unique_constraint(None, 'dining_check', ['client_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dining_check', type_='unique')
    op.drop_index('uq_check_open_per_table', table_name='dining_check', postgresql_where="status = 'open' AND table_id IS NOT NULL")
    op.create_index(op.f('ix_check_open_table'), 'dining_check', ['table_id'], unique=False, postgresql_where="(status = 'open'::text)")
    op.drop_column('dining_check', 'client_uuid')
    # ### end Alembic commands ###
