"""menu open price and togo sources

Revision ID: 407849df4b45
Revises: 41725eab6472
Create Date: 2026-08-10 01:59:50.676122
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '407849df4b45'
down_revision: Union[str, None] = '41725eab6472'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ⚠️ 第四次了：autogenerate **检测不到 CHECK 约束表达式的变化**
    #    （名字没变、只有表达式变了）。每次改 CHECK 都必须人工核对生成的迁移。
    #
    #    这次两条都要改，而且 source 不是单纯放宽 —— 'pickup' 被拆成了
    #    'phone_order' 和 'buffet_togo'。所以顺序是：
    #      drop 旧约束 → 迁移数据 → 建新约束
    op.drop_constraint("ck_check_source", "dining_check", type_="check")
    op.drop_constraint(
        "ck_check_table_matches_source", "dining_check", type_="check"
    )

    # 历史上的 pickup 单一律当作电话点菜
    op.execute("UPDATE dining_check SET source = 'phone_order' WHERE source = 'pickup'")

    op.create_check_constraint(
        "ck_check_source",
        "dining_check",
        "source IN ('dine_in','phone_order','buffet_togo')",
    )
    op.create_check_constraint(
        "ck_check_table_matches_source",
        "dining_check",
        "(source = 'dine_in') = (table_id IS NOT NULL)",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    # ⚠️ 给**已有数据**的表加 NOT NULL 列，必须带 server_default ——
    #    否则现有行是 NULL，直接 NotNullViolation。
    #    加完可以把默认值去掉（让应用层负责），但这里保留无害。
    op.add_column(
        'menu_item',
        sa.Column('open_price', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'open_price')
    # ### end Alembic commands ###
