"""menu open price and togo sources

Revision ID: 407849df4b45
Revises: 41725eab6472
Create Date: 2026-08-10 01:59:50.676122
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '407849df4b45'
down_revision: Union[str, None] = '41725eab6472'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ⚠️ Fourth time: autogenerate **cannot see a CHECK expression change**
    #    (the name stays, only the expression moves). Every CHECK change needs the generated migration read by a person.
    #
    #    Both change here, and source is not simply relaxed -- 'pickup' splits
    #    into 'phone_order' and 'buffet_togo'. So the order is:
    #      drop the old constraint -> migrate the data -> create the new one
    op.drop_constraint("ck_check_source", "dining_check", type_="check")
    op.drop_constraint(
        "ck_check_table_matches_source", "dining_check", type_="check"
    )

    # Every historical pickup check counts as a phone order
    op.execute("UPDATE dining_check SET source = 'phone_order' WHERE source = 'pickup'")

    op.create_check_constraint(
        "ck_check_source",
        "dining_check",
        "source IN ('dine_in','phone_order','buffet_togo')",
    )
    op.create_check_constraint(
        "ck_check_table_matches_source",
        "dining_check",
        "(source = 'dine_in') = (table_id IS NOT NULL)",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    # ⚠️ Adding a NOT NULL column to a table that **already has rows** needs a
    #    server_default, or the existing rows are NULL and it is a NotNullViolation.
    #    The default can be dropped afterwards (leaving it to the application); keeping it here is harmless.
    op.add_column(
        'menu_item',
        sa.Column('open_price', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'open_price')
    # ### end Alembic commands ###
