"""single daily tip total

Revision ID: 41725eab6472
Revises: af8ab7e77282
Create Date: 2026-08-10 00:27:46.657571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41725eab6472'
down_revision: Union[str, None] = 'af8ab7e77282'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('tips_total_cents', sa.Integer(), nullable=True))
    # 先把已有的拆分小费合进总数，再删列 —— 顺序反了数据就没了。
    # autogenerate 只会生成 DDL，这段永远要自己补。
    op.execute(
        "UPDATE daily_batch SET tips_total_cents ="
        " COALESCE(reported_cash_tips_cents, 0) + COALESCE(reported_card_tips_cents, 0)"
        " WHERE reported_cash_tips_cents IS NOT NULL"
        "    OR reported_card_tips_cents IS NOT NULL"
    )
    op.drop_column('daily_batch', 'reported_card_tips_cents')
    op.drop_column('daily_batch', 'reported_cash_tips_cents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('reported_cash_tips_cents', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('daily_batch', sa.Column('reported_card_tips_cents', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('daily_batch', 'tips_total_cents')
    # ### end Alembic commands ###
