"""reversible void

Revision ID: 94b212c0ea73
Revises: 1e18aeaf89d6
Create Date: 2026-08-09 22:51:10.797887
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94b212c0ea73'
down_revision: Union[str, None] = '1e18aeaf89d6'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_exception', sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('check_exception', sa.Column('reverted_by', sa.BigInteger(), nullable=True))
    op.add_column('check_exception', sa.Column('revert_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'check_exception', 'app_user', ['reverted_by'], ['id'])
    op.add_column('dining_check', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dining_check', sa.Column('pre_void_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dining_check', 'pre_void_status')
    op.drop_column('dining_check', 'voided_at')
    op.drop_constraint(None, 'check_exception', type_='foreignkey')
    op.drop_column('check_exception', 'revert_reason')
    op.drop_column('check_exception', 'reverted_by')
    op.drop_column('check_exception', 'reverted_at')
    # ### end Alembic commands ###
