"""transfer merge payment service charge

Revision ID: aa399012e825
Revises: 94b212c0ea73
Create Date: 2026-08-09 23:19:33.603055
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa399012e825'
down_revision: Union[str, None] = '94b212c0ea73'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dining_check', sa.Column('merged_into', sa.UUID(), nullable=True))
    op.add_column('dining_check', sa.Column('service_charge_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('dining_check', sa.Column('service_charge_rate', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('dining_check', sa.Column('payment_method', sa.Text(), nullable=True))
    op.add_column('dining_check', sa.Column('paid_cash_cents', sa.Integer(), nullable=True))
    op.add_column('dining_check', sa.Column('paid_card_cents', sa.Integer(), nullable=True))
    op.add_column('dining_check', sa.Column('paid_other_cents', sa.Integer(), nullable=True))
    op.add_column('dining_check', sa.Column('payment_note', sa.Text(), nullable=True))
    op.create_check_constraint('ck_check_payment_method', 'dining_check', "payment_method IS NULL OR payment_method IN ('cash','card','mixed','other')")

    # ⚠️ Third time in the same hole: autogenerate **cannot see ck_check_status
    #    change** -- the name stayed and only 'merged' was added to the
    #    expression. Hand-written. This one **relaxes** the constraint (one
    #    more allowed value), so drop and create is enough and no data migration is needed.
    op.drop_constraint("ck_check_status", "dining_check", type_="check")
    op.create_check_constraint(
        "ck_check_status",
        "dining_check",
        "status IN ('open','closed','voided','merged')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_check_payment_method', 'dining_check', type_='check')
    op.drop_column('dining_check', 'payment_note')
    op.drop_column('dining_check', 'paid_other_cents')
    op.drop_column('dining_check', 'paid_card_cents')
    op.drop_column('dining_check', 'paid_cash_cents')
    op.drop_column('dining_check', 'payment_method')
    op.drop_column('dining_check', 'service_charge_rate')
    op.drop_column('dining_check', 'service_charge_cents')
    op.drop_column('dining_check', 'merged_into')
    # ### end Alembic commands ###
