"""daily tips

Revision ID: af8ab7e77282
Revises: aa399012e825
Create Date: 2026-08-10 00:20:47.023116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af8ab7e77282'
down_revision: Union[str, None] = 'aa399012e825'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('tips_updated_by', sa.BigInteger(), nullable=True))
    op.add_column('daily_batch', sa.Column('tips_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('daily_batch', 'computed_admission_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'computed_drink_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'computed_item_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'computed_total_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'guest_adult',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'guest_child',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'guest_senior',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'check_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_batch', 'exception_total_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'daily_batch', 'app_user', ['tips_updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_batch', type_='foreignkey')
    op.alter_column('daily_batch', 'exception_total_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'check_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'guest_senior',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'guest_child',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'guest_adult',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'computed_total_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'computed_item_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'computed_drink_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_batch', 'computed_admission_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('daily_batch', 'tips_updated_at')
    op.drop_column('daily_batch', 'tips_updated_by')
    # ### end Alembic commands ###
