"""initial schema

Revision ID: b29d0404d06b
Revises: 
Create Date: 2026-08-09 20:35:39.478883
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b29d0404d06b'
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('front','kitchen','admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buffet_price',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('period_kind', sa.Text(), nullable=False),
    sa.Column('charge_kind', sa.Text(), nullable=False),
    sa.Column('guest_type', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.CheckConstraint("charge_kind <> 'admission' OR guest_type IS NOT NULL", name='ck_bp_admission_needs_guest_type'),
    sa.CheckConstraint("charge_kind IN ('admission','drink')", name='ck_bp_kind'),
    sa.CheckConstraint("guest_type IS NULL OR guest_type IN ('adult','child','senior')", name='ck_bp_guest_type'),
    sa.CheckConstraint("period_kind IN ('lunch','dinner')", name='ck_bp_period'),
    sa.CheckConstraint('price_cents >= 0', name='ck_bp_price_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('dining_table',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('zone', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('is_buffet_dish', sa.Boolean(), nullable=False),
    sa.Column('station', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("station IN ('wok','fryer','cold','drink','none')", name='ck_menu_station'),
    sa.CheckConstraint('price_cents IS NULL OR price_cents >= 0', name='ck_menu_price_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_item_active', 'menu_item', ['active', 'category'], unique=False)
    op.create_table('service_period',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('lunch','dinner')", name='ck_period_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date', 'kind', name='uq_period_date_kind')
    )
    op.create_table('auth_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_session_user_active', 'auth_session', ['user_id', 'expires_at'], unique=False)
    op.create_table('daily_batch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('computed_admission_cents', sa.Integer(), nullable=False),
    sa.Column('computed_drink_cents', sa.Integer(), nullable=False),
    sa.Column('computed_item_cents', sa.Integer(), nullable=False),
    sa.Column('computed_total_cents', sa.Integer(), nullable=False),
    sa.Column('guest_adult', sa.Integer(), nullable=False),
    sa.Column('guest_child', sa.Integer(), nullable=False),
    sa.Column('guest_senior', sa.Integer(), nullable=False),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('exception_total_cents', sa.Integer(), nullable=False),
    sa.Column('reported_card_cents', sa.Integer(), nullable=True),
    sa.Column('reported_card_tips_cents', sa.Integer(), nullable=True),
    sa.Column('reported_cash_cents', sa.Integer(), nullable=True),
    sa.Column('reported_cash_tips_cents', sa.Integer(), nullable=True),
    sa.Column('variance_cents', sa.Integer(), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_date')
    )
    op.create_table('dining_check',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('table_id', sa.BigInteger(), nullable=True),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("(source = 'dine_in' AND table_id IS NOT NULL) OR (source = 'pickup' AND table_id IS NULL)", name='ck_check_table_matches_source'),
    sa.CheckConstraint("source IN ('dine_in','pickup')", name='ck_check_source'),
    sa.CheckConstraint("status IN ('open','closed','voided')", name='ck_check_status'),
    sa.ForeignKeyConstraint(['opened_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['service_period.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['dining_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_open_table', 'dining_check', ['table_id'], unique=False, postgresql_where="status = 'open'")
    op.create_index('ix_check_period_status', 'dining_check', ['period_id', 'status'], unique=False)
    op.create_table('sync_op',
    sa.Column('op_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('op_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_seq', sa.BigInteger(), nullable=False),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('op_id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index('ix_sync_op_applied_seq', 'sync_op', ['seq'], unique=False, postgresql_where='applied_at IS NOT NULL')
    op.create_table('tray_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('menu_item_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('fill_level', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("event_type IN ('refill','half','empty','discard')", name='ck_tray_type'),
    sa.CheckConstraint('fill_level IS NULL OR (fill_level >= 0 AND fill_level <= 1)', name='ck_tray_fill_range'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tray_item_time', 'tray_event', ['menu_item_id', 'observed_at'], unique=False)
    op.create_table('check_exception',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recorded_by', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('walkout','comp','discount','void','remake','other')", name='ck_exc_kind'),
    sa.CheckConstraint('length(btrim(reason)) > 0', name='ck_exc_reason_nonempty'),
    sa.ForeignKeyConstraint(['approved_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['dining_check.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exception_time', 'check_exception', ['recorded_at'], unique=False)
    op.create_table('head_charge',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('guest_type', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint("guest_type IS NULL OR guest_type IN ('adult','child','senior')", name='ck_head_guest_type'),
    sa.CheckConstraint("kind <> 'admission' OR guest_type IS NOT NULL", name='ck_head_admission_needs_guest_type'),
    sa.CheckConstraint("kind IN ('admission','drink')", name='ck_head_kind'),
    sa.CheckConstraint('qty > 0', name='ck_head_qty_pos'),
    sa.CheckConstraint('unit_price_cents >= 0', name='ck_head_price_nonneg'),
    sa.ForeignKeyConstraint(['check_id'], ['dining_check.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_head_charge_check', 'head_charge', ['check_id'], unique=False)
    op.create_table('order_line',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_item_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('placed','fired','ready','served','voided')", name='ck_line_status'),
    sa.CheckConstraint('qty > 0', name='ck_line_qty_pos'),
    sa.CheckConstraint('unit_price_cents >= 0', name='ck_line_price_nonneg'),
    sa.ForeignKeyConstraint(['check_id'], ['dining_check.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_line_check', 'order_line', ['check_id'], unique=False)
    op.create_index('ix_order_line_open', 'order_line', ['status', 'placed_at'], unique=False)
    op.create_table('pickup_order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('phone_last4', sa.String(length=4), nullable=True),
    sa.Column('promised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("phone_last4 IS NULL OR phone_last4 ~ '^[0-9]{4}$'", name='ck_pickup_phone_last4'),
    sa.CheckConstraint("status IN ('placed','ready','picked_up','no_show','voided')", name='ck_pickup_status'),
    sa.ForeignKeyConstraint(['check_id'], ['dining_check.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_id')
    )
    op.create_table('ping_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('op_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['sync_op.op_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('op_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ping_event')
    op.drop_table('pickup_order')
    op.drop_index('ix_order_line_open', table_name='order_line')
    op.drop_index('ix_order_line_check', table_name='order_line')
    op.drop_table('order_line')
    op.drop_index('ix_head_charge_check', table_name='head_charge')
    op.drop_table('head_charge')
    op.drop_index('ix_exception_time', table_name='check_exception')
    op.drop_table('check_exception')
    op.drop_index('ix_tray_item_time', table_name='tray_event')
    op.drop_table('tray_event')
    op.drop_index('ix_sync_op_applied_seq', table_name='sync_op', postgresql_where='applied_at IS NOT NULL')
    op.drop_table('sync_op')
    op.drop_index('ix_check_period_status', table_name='dining_check')
    op.drop_index('ix_check_open_table', table_name='dining_check', postgresql_where="status = 'open'")
    op.drop_table('dining_check')
    op.drop_table('daily_batch')
    op.drop_index('ix_session_user_active', table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_table('service_period')
    op.drop_index('ix_menu_item_active', table_name='menu_item')
    op.drop_table('menu_item')
    op.drop_table('dining_table')
    op.drop_table('device')
    op.drop_table('buffet_price')
    op.drop_table('app_user')
    # ### end Alembic commands ###
