"""store setting: timezone and business-day cutoff

Revision ID: b3d5c81a4e17
Revises: f816387a2ece
Create Date: 2026-08-10

Hand-written, not autogenerated, for two reasons:
  1. autogenerate never emits a data migration, and this single-row table
     **has to** be created with its row -- an empty one sends period.py back
     to the env default, so what Settings shows is not what is in force.
  2. CHECK expressions are not reliably detected (four times now).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3d5c81a4e17'
down_revision: Union[str, None] = 'f816387a2ece'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'store_setting',
        # Single-row table, id is always 1 -- no sequence
        sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('tz', sa.Text(), nullable=False),
        sa.Column('business_day_cutoff_hour', sa.Integer(), nullable=False),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('id = 1', name='ck_store_setting_singleton'),
        sa.CheckConstraint(
            'business_day_cutoff_hour >= 0 AND business_day_cutoff_hour < 24',
            name='ck_store_setting_cutoff_range',
        ),
        sa.ForeignKeyConstraint(['updated_by'], ['app_user.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    # Data migration: the row goes in with the table.
    #
    # The default is America/Los_Angeles -- the store is in Douglas County NV, on Pacific time.
    # The code before this hard-coded UTC-5 (EST), two hours out, which
    # charged dinner prices from 13:00. Settings can change it, and a wrong one is just changed again.
    op.execute(
        """
        INSERT INTO store_setting (id, tz, business_day_cutoff_hour)
        VALUES (1, 'America/Los_Angeles', 0)
        ON CONFLICT (id) DO NOTHING
        """
    )


def downgrade() -> None:
    op.drop_table('store_setting')
