"""buffet board: dishes by period/page/slot, tray_event points at it

Revision ID: d7a2f4c19b60
Revises: c4e91f27a8b3
Create Date: 2026-08-11

Hand-written, not autogenerated: seed data is never generated, and CHECK
expression changes are not reliably detected (four times now).

tray_event used to hang off menu_item. What is out on the buffet and what can
be ordered are different things, and there are far more of the former than the
twelve menu rows flagged is_buffet_dish. The foreign key moves while
tray_event is **still empty** -- doing it later would need a data migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7a2f4c19b60'
down_revision: Union[str, None] = 'c4e91f27a8b3'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'buffet_dish',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('period_kind', sa.Text(), nullable=False),
        sa.Column('page', sa.Integer(), nullable=False),
        sa.Column('pos', sa.Integer(), nullable=False),
        sa.Column('name_zh', sa.Text(), nullable=False),
        sa.Column('name_en', sa.Text(), nullable=False, server_default=''),
        sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.CheckConstraint("period_kind IN ('lunch','dinner')", name='ck_bd_period'),
        sa.CheckConstraint('page BETWEEN 1 AND 3', name='ck_bd_page'),
        sa.CheckConstraint('pos BETWEEN 1 AND 10', name='ck_bd_pos'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_bd_layout', 'buffet_dish', ['period_kind', 'page', 'pos'])

    # Seed: the twelve dishes already flagged is_buffet_dish, once for lunch and once for dinner.
    # Real names rather than "placeholder 1 / placeholder 2" -- the owner can
    # use it straight away, and the remaining slots stay empty to fill in.
    #
    # ⚠️ The same dish is **two rows**, lunch and dinner. They are two different
    #    consumption processes; one row would only have to be split again in the model.
    op.execute(
        """
        INSERT INTO buffet_dish (period_kind, page, pos, name_zh, name_en)
        SELECT p.kind,
               ((r.rn - 1) / 10) + 1,
               ((r.rn - 1) % 10) + 1,
               r.name_zh,
               r.name_en
          FROM (SELECT 'lunch' AS kind UNION ALL SELECT 'dinner') p
         CROSS JOIN (
                SELECT name_zh, name_en,
                       row_number() OVER (ORDER BY sort_order, id) AS rn
                  FROM menu_item
                 WHERE is_buffet_dish
               ) r
         WHERE r.rn <= 30
        """
    )

    # tray_event: move the foreign key. The table is empty, so do it directly.
    op.drop_index('ix_tray_item_time', table_name='tray_event')
    op.drop_column('tray_event', 'menu_item_id')
    op.add_column(
        'tray_event', sa.Column('buffet_dish_id', sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        'fk_tray_dish', 'tray_event', 'buffet_dish', ['buffet_dish_id'], ['id']
    )
    op.create_index('ix_tray_dish_time', 'tray_event', ['buffet_dish_id', 'observed_at'])


def downgrade() -> None:
    op.drop_index('ix_tray_dish_time', table_name='tray_event')
    op.drop_constraint('fk_tray_dish', 'tray_event', type_='foreignkey')
    op.drop_column('tray_event', 'buffet_dish_id')
    # A downgrade loses what the refill records point at -- clear it first, or NOT NULL cannot be added
    op.execute('DELETE FROM tray_event')
    op.add_column(
        'tray_event', sa.Column('menu_item_id', sa.BigInteger(), nullable=False)
    )
    op.create_index('ix_tray_item_time', 'tray_event', ['menu_item_id', 'observed_at'])

    op.drop_index('ix_bd_layout', table_name='buffet_dish')
    op.drop_table('buffet_dish')
