"""drink tiers by guest type

Revision ID: e868c96c898a
Revises: 292fb55f28d9
Create Date: 2026-08-09 21:59:04.091585
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e868c96c898a'
down_revision: Union[str, None] = '292fb55f28d9'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ⚠️ 手动补的数据回填 —— **autogenerate 永远不会生成数据迁移**。
    #
    # 改动之前，饮料只有一档、`guest_type` 是 NULL。现在要 SET NOT NULL，
    # 那些历史行会直接把迁移炸掉。语义上它们就是"按成人价收的饮料"，
    # 所以回填成 'adult'。
    #
    # 必须放在 SET NOT NULL **之前**，顺序错了迁移就失败。
    op.execute("UPDATE buffet_price SET guest_type = 'adult' WHERE guest_type IS NULL")
    op.execute("UPDATE head_charge  SET guest_type = 'adult' WHERE guest_type IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buffet_price', 'guest_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('ck_bp_admission_needs_guest_type'), 'buffet_price', type_='check')
    op.create_check_constraint('ck_bp_drink_tier', 'buffet_price', "charge_kind <> 'drink' OR guest_type IN ('adult','child')")
    op.alter_column('head_charge', 'guest_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('ck_head_admission_needs_guest_type'), 'head_charge', type_='check')
    op.create_check_constraint('ck_head_drink_tier', 'head_charge', "kind <> 'drink' OR guest_type IN ('adult','child')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_head_drink_tier', 'head_charge', type_='check')
    op.create_check_constraint(op.f('ck_head_admission_needs_guest_type'), 'head_charge', "kind <> 'admission'::text OR guest_type IS NOT NULL")
    op.alter_column('head_charge', 'guest_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('ck_bp_drink_tier', 'buffet_price', type_='check')
    op.create_check_constraint(op.f('ck_bp_admission_needs_guest_type'), 'buffet_price', "charge_kind <> 'admission'::text OR guest_type IS NOT NULL")
    op.alter_column('buffet_price', 'guest_type',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
