"""tax rate

Revision ID: f816387a2ece
Revises: 407849df4b45
Create Date: 2026-08-10 02:14:14.378001
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f816387a2ece'
down_revision: Union[str, None] = '407849df4b45'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate >= 0 AND rate < 1', name='ck_tax_rate_range'),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_from', name='uq_tax_rate_effective')
    )
    op.add_column('dining_check', sa.Column('tax_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('dining_check', sa.Column('tax_rate', sa.Numeric(precision=6, scale=5), nullable=True))
    op.alter_column('menu_item', 'open_price',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_item', 'open_price',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('dining_check', 'tax_rate')
    op.drop_column('dining_check', 'tax_cents')
    op.drop_table('tax_rate')
    # ### end Alembic commands ###
